# --- Main Colors ---
background            #0f1416
foreground            #dee3e6
cursor                #dee3e6
cursor_text_color     #0f1416

selection_background  #344a52
selection_foreground  #cfe6f1

url_color             #c3c3eb

# --- ANSI Colors ---
color0                #0f1416
color1                #ffb4ab
color2                #c3c3eb
color3                #b3cad4
color4                #88d1ec
color5                #c3c3eb
color6                #b3cad4
color7                #dee3e6

color8                #40484c
color9                #93000a
color10               #434465
color11               #344a52
color12               #004e61
color13               #344a52
color14               #434465
color15               #bfc8cc

# --- Starship Prompt Bubbles ---
color255              #004e61
color254              #88d1ec
color253              #344a52
color252              #b3cad4
color251              #434465
color250              #c3c3eb
color249              #93000a
color248              #ffb4ab

color232              #b7eaff
color233              #003543
color234              #cfe6f1
color235              #1e333b
color236              #e1e0ff
color237              #2c2e4d
color238              #ffdad6
color239              #690005
color240              #b7eaff

# Matched with unthemed light/dark
color243              #88d1ec
color244              #ffb4ab
color245              #40484c

# --- UI Elements ---
active_tab_foreground   #003543
active_tab_background   #88d1ec
inactive_tab_foreground #b7eaff
inactive_tab_background #004e61

active_border_color     #88d1ec
inactive_border_color   #8a9296

# --- Marks ---
mark1_foreground        #001f28
mark1_background        #b7eaff
mark2_foreground        #071e26
mark2_background        #cfe6f1
mark3_foreground        #171837
mark3_background        #e1e0ff
