# --- Main Colors ---
background            #0e1415
foreground            #dee3e5
cursor                #dee3e5
cursor_text_color     #0e1415

selection_background  #334b4f
selection_foreground  #cde7ec

url_color             #bac6ea

# --- ANSI Colors ---
color0                #0e1415
color1                #ffb4ab
color2                #bac6ea
color3                #b1cbd0
color4                #82d3e1
color5                #bac6ea
color6                #b1cbd0
color7                #dee3e5

color8                #3f484a
color9                #93000a
color10               #3b4665
color11               #334b4f
color12               #004f58
color13               #334b4f
color14               #3b4665
color15               #bfc8ca

# --- Starship Prompt Bubbles ---
color255              #004f58
color254              #82d3e1
color253              #334b4f
color252              #b1cbd0
color251              #3b4665
color250              #bac6ea
color249              #93000a
color248              #ffb4ab

color232              #9eeffd
color233              #00363d
color234              #cde7ec
color235              #1c3438
color236              #dae2ff
color237              #24304d
color238              #ffdad6
color239              #690005
color240              #9eeffd

# Matched with unthemed light/dark
color243              #82d3e1
color244              #ffb4ab
color245              #3f484a

# --- UI Elements ---
active_tab_foreground   #00363d
active_tab_background   #82d3e1
inactive_tab_foreground #9eeffd
inactive_tab_background #004f58

active_border_color     #82d3e1
inactive_border_color   #899294

# --- Marks ---
mark1_foreground        #001f24
mark1_background        #9eeffd
mark2_foreground        #051f23
mark2_background        #cde7ec
mark3_foreground        #0e1a37
mark3_background        #dae2ff
