# --- Main Colors ---
background            #0e1514
foreground            #dde4e3
cursor                #dde4e3
cursor_text_color     #0e1514

selection_background  #324b4b
selection_foreground  #cce8e8

url_color             #b3c8e9

# --- ANSI Colors ---
color0                #0e1514
color1                #ffb4ab
color2                #b3c8e9
color3                #b0cccb
color4                #80d4d5
color5                #b3c8e9
color6                #b0cccb
color7                #dde4e3

color8                #3f4948
color9                #93000a
color10               #344863
color11               #324b4b
color12               #004f50
color13               #324b4b
color14               #344863
color15               #bec8c8

# --- Starship Prompt Bubbles ---
color255              #004f50
color254              #80d4d5
color253              #324b4b
color252              #b0cccb
color251              #344863
color250              #b3c8e9
color249              #93000a
color248              #ffb4ab

color232              #9cf1f2
color233              #003737
color234              #cce8e8
color235              #1b3435
color236              #d4e3ff
color237              #1d314b
color238              #ffdad6
color239              #690005
color240              #9cf1f2

# Matched with unthemed light/dark
color243              #80d4d5
color244              #ffb4ab
color245              #3f4948

# --- UI Elements ---
active_tab_foreground   #003737
active_tab_background   #80d4d5
inactive_tab_foreground #9cf1f2
inactive_tab_background #004f50

active_border_color     #80d4d5
inactive_border_color   #899392

# --- Marks ---
mark1_foreground        #002020
mark1_background        #9cf1f2
mark2_foreground        #041f20
mark2_background        #cce8e8
mark3_foreground        #051c35
mark3_background        #d4e3ff
