cursor            #80d4d5
cursor_text_color #003737

foreground            #dde4e3
background            #0e1514
background_opacity    0.60
selection_foreground  #1b3435
selection_background  #b0cccb
url_color             #b0cccb

color0  #0e1514
color8  #2f3636

# Dark mode ANSI colors (Tomorrow Night)
color1  #f2777a
color9  #f2777a
color2  #99cc99
color10 #99cc99
color3  #ffcc66
color11 #ffcc66
color4  #6699cc
color12 #6699cc
color5  #cc99cc
color13 #cc99cc
color6  #66cccc
color14 #66cccc


color7  #bec8c8
color15 #dde4e3

mark1_foreground #002020
mark1_background #9cf1f2
mark2_foreground #041f20
mark2_background #cce8e8
mark3_foreground #051c35
mark3_background #d4e3ff

active_tab_foreground #003737
active_tab_background #80d4d5
inactive_tab_foreground #9cf1f2
inactive_tab_background #004f50

active_border_color #80d4d5
inactive_border_color #003737
