# --- Main Colors ---
background            #15140c
foreground            #e7e2d5
cursor                #e7e2d5
cursor_text_color     #15140c

selection_background  #4b472b
selection_foreground  #eae3bd

url_color             #a7d0b8

# --- ANSI Colors ---
color0                #15140c
color1                #ffb4ab
color2                #a7d0b8
color3                #cec7a3
color4                #d4c871
color5                #a7d0b8
color6                #cec7a3
color7                #e7e2d5

color8                #49473a
color9                #93000a
color10               #284e3b
color11               #4b472b
color12               #4f4800
color13               #4b472b
color14               #284e3b
color15               #cbc6b5

# --- Starship Prompt Bubbles ---
color255              #4f4800
color254              #d4c871
color253              #4b472b
color252              #cec7a3
color251              #284e3b
color250              #a7d0b8
color249              #93000a
color248              #ffb4ab

color232              #f1e58a
color233              #363100
color234              #eae3bd
color235              #343117
color236              #c2ecd3
color237              #103726
color238              #ffdad6
color239              #690005
color240              #f1e58a

# Matched with unthemed light/dark
color243              #d4c871
color244              #ffb4ab
color245              #49473a

# --- UI Elements ---
active_tab_foreground   #363100
active_tab_background   #d4c871
inactive_tab_foreground #f1e58a
inactive_tab_background #4f4800

active_border_color     #d4c871
inactive_border_color   #959181

# --- Marks ---
mark1_foreground        #1f1c00
mark1_background        #f1e58a
mark2_foreground        #1f1c05
mark2_background        #eae3bd
mark3_foreground        #002113
mark3_background        #c2ecd3
