cursor            #b0c6ff
cursor_text_color #142e60

foreground            #e2e2e9
background            #121318
background_opacity    0.60
selection_foreground  #293042
selection_background  #bfc6dc
url_color             #bfc6dc

color0  #121318
color8  #33353a

# Dark mode ANSI colors (Tomorrow Night)
color1  #f2777a
color9  #f2777a
color2  #99cc99
color10 #99cc99
color3  #ffcc66
color11 #ffcc66
color4  #6699cc
color12 #6699cc
color5  #cc99cc
color13 #cc99cc
color6  #66cccc
color14 #66cccc


color7  #c5c6d0
color15 #e2e2e9

mark1_foreground #001944
mark1_background #d9e2ff
mark2_foreground #141b2c
mark2_background #dce2f9
mark3_foreground #2a132c
mark3_background #fdd7fa

active_tab_foreground #142e60
active_tab_background #b0c6ff
inactive_tab_foreground #d9e2ff
inactive_tab_background #2e4578

active_border_color #b0c6ff
inactive_border_color #142e60
